//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balance()
        {
            this.LogWriteOff = new HashSet<LogWriteOff>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdMedicine { get; set; }
        public Nullable<int> IdHospitalDepartment { get; set; }
        public string ImplementationMonth { get; set; }
        public string ImplementationYear { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual HospitalDepartament HospitalDepartament { get; set; }
        public virtual Medicine Medicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogWriteOff> LogWriteOff { get; set; }
    }
}
