//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOfReceipts
    {
        public int Id { get; set; }
        public Nullable<int> IdMedicine { get; set; }
        public Nullable<System.DateTime> DateRecepts { get; set; }
        public Nullable<int> QuantityReceipts { get; set; }
        public string ImplementationMonth { get; set; }
        public string ImplementationYear { get; set; }
        public Nullable<int> IdHospitalDepartament { get; set; }
    
        public virtual HospitalDepartament HospitalDepartament { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
