//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogWriteOff
    {
        public int Id { get; set; }
        public Nullable<int> IdBalance { get; set; }
        public Nullable<System.DateTime> DateWrite { get; set; }
        public Nullable<int> QuantityWrite { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public string Reason { get; set; }
    
        public virtual Balance Balance { get; set; }
    }
}
