//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDeyails = new HashSet<OrderDeyails>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<int> IdDepartament { get; set; }
        public Nullable<int> IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HospitalDepartament HospitalDepartament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDeyails> OrderDeyails { get; set; }
    }
}
