//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom_Hospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDeyails
    {
        public int id { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> IdMedicine { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
